version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - "vendor"
    - "resources"
  skip-files:
    - ".*\\.png$"
  include:
    - "src/internal/..."
    - "src/cmd/..."

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gocritic
    - ineffassign
    - misspell
    - dupl
    - bodyclose
  disable:
    - funlen

issues:
  max-same-issues: 3
  max-issues-per-linter: 50

linters-settings:
  dupl:
    threshold: 50
  gocritic:
    disabled-checks:
      - commentFormatting
  goimports:
    local-prefixes: "github.com/ce-fello/pr-reviewer-service"
